#!/usr/bin/env python

# Written by Luca Falavigna
# (C) 2007, Luca Falavigna

import os
from re import findall
from sys import exit

def select_package(directory):
	try:
		filelist = os.listdir(directory)
	except:
		print 'Unable to access directory %s' % directory
		exit(1)
	for filename in filelist:
		package = os.path.splitext(filename)
		if package[1] == '.dsc':
			return package[0]
	return None

def parse_packages(package):
	try:
		fd = os.open(package, os.O_RDONLY)
	except:
		print 'Unable to access file %s' % package
		exit(1)
	files =findall('\s\w+\s\d+\s(.*)', os.read(fd, os.fstat(fd).st_size))
	files.insert(len(files), package)
	os.close(fd)
	return files
