#!/usr/bin/env python

# Written by Luca Falavigna
# (C) 2007, Luca Falavigna

import os
from re import findall
from sys import exit

def select_dsc(directory):
	try:
		filelist = os.listdir(directory)
	except:
		print 'Unable to access directory %s' % directory
		exit(1)
	for filename in filelist:
		if os.path.splitext(filename)[1] == '.dsc':
			return filename
	return None

def parse_packages(directory, package):
	try:
		fd = os.open(os.path.join(directory, package), os.O_RDONLY)
	except:
		print 'Unable to open %s' % os.path.join(directory, package)
		exit(1)
	files =findall('\s\w+\s\d+\s(.*)', os.read(fd, os.fstat(fd).st_size))
	files.insert(len(files), package)
	os.close(fd)
	return files
