#!/usr/bin/env python

# Written by Luca Falavigna
# (C) 2007, Luca Falavigna

from os import listdir
from os.path import splitext
from sys import exit

def select_package(directory):
	try:
		filelist = listdir(directory)
	except:
		print 'Unable to access directory %s' % directory
		exit(1)
	for filename in filelist:
		package = splitext(filename)
		if package[1] == '.dsc':
			return package[0]
	return None
