#!/bin/sh

apt-get install -y iptables

# GID must match the one defined by BUILDUSERID into pbuilderrc file
iptables -A OUTPUT -m owner --gid-owner 1234 -j REJECT --reject-with icmp-port-unreachable 
