#!/bin/sh
# This forces apt to wait if apt-ftparchive is running from a parallel build

LOCKDIR=/build/.debomatic
LOCKFILE=$LOCKDIR/$1-$2.$3.apt.lock
LOCKFILEUPDATE=$LOCKDIR/$2-$3.apt.lock.update
mkdir -p $LOCKDIR
while [ -f $LOCKFILEUPDATE ]
do
	sleep 5
done
touch $LOCKFILE
