#!/bin/sh
# this forces dpkg not to call sync() after package extraction and leads to 1-2 packages installed per second.
# reference: https://wiki.ubuntu.com/PbuilderHowto#dpkg_setting

echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/02apt-speedup
