#! /bin/sh
### BEGIN INIT INFO
# Provides:          debomatic
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Package autobuilder
# Description:       Automatic build machine for Debian source packages.
### END INIT INFO

NAME=debomatic

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON=/usr/bin/debomatic
DAEMON_ARGS="-c $DEBOMATIC_CONFIG_FILE $DEBOMATIC_OPTS"
SCRIPTNAME=/etc/init.d/$NAME

[ -x "$DAEMON" ] || exit 0
[ "$DEBOMATIC_AUTOSTART" = 0  ] && exit 0

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
	$DAEMON $DAEMON_ARGS
}

do_stop()
{
	$DAEMON -q
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		log_end_msg 1
		;;
	esac
	;;
  status)
	status_of_proc /usr/bin/$NAME $NAME
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
