.TH debomatic.conf 5 2007\-05\-13  
.SH NAME
debomatic.conf \- Configuration files for debomatic
.SH "DEFAULT SECTION"
\fIpackagedir\fR: the directory where debomatic will 
search for source packages to build
.PP
\fIconfigdir\fR: the directory where debomatic will 
search for configuration files
.PP
\fIlogfile\fR: debomatic messages will be stored in this file
.PP
\fIsleep\fR: interval between two scans or builds
.SH "SEE ALSO"
debomatic(1), pbuilderrc(5)
