.TH debomatic 1 2007\-03\-07  
.SH NAME
debomatic \- Automatic build machine for Debian packages
.SH SYNOPSIS
\fBdebomatic\fR 
\fB<configuration file>\fR
.SH DESCRIPTION
This tool provides a simple build machine for Debian source packages.
It is designed to be self\-sufficient and requires just an initial setup.
It needs pbuilder and an active Internet 
connection in order to work properly.
.PP
You have to run it using root privileges because of 
pbuilder infrastructure.
.SH COPYRIGHT
This manual page was written by Luca Falavigna 
<dktrkranz@linuxdc.it>. Permission is granted to copy, distribute 
and/or modify this document under the terms of the 
GNU General Public License, Version 2 or any later 
version published by the Free Software Foundation.
.PP
On Debian systems (like Ubuntu), the complete text of the GNU General
Public License can be found in
\fB/usr/share/common\-licenses/GPL\fR.
.SH "SEE ALSO"
debomatic.conf(5)
