#!/bin/sh

if [ "$(uname -s)" = "Linux" ]
then
	if [ -f /usr/bin/dpkg-buildpackage-debomatic-original ]
	then
		mv /usr/bin/dpkg-buildpackage-debomatic-original /usr/bin/dpkg-buildpackage
		rm /usr/bin/dpkg-buildpackage-debomatic-wrapper
		apt-get --purge autoremove -y net-tools
	fi
fi
